import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../Components/Footer";
import FooterWrapper from "../Components/FooterWrapper"; // NEW
import NavbarNew from "../Components/NavbarNew";
import NavWrapper from "src/Components/NavWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <p className="text-red-500 text-center text-2xl font-bold">
          Page Not Found
        </p>
        {/* <NavWrapper>
          <NavbarNew />
        </NavWrapper>
        <div>
          {children}

          <FooterWrapper>
            <Footer />
          </FooterWrapper>
        </div> */}
      </body>
    </html>
  );
}
